# Generated by Django 5.2.7 on 2025-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_customer_created_at_order_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
